sudo: required
services:
  - docker
before_install: |
  export PATH=$PATH:HOME/.local/bin
  docker build -t $REGISTRY/$REPO_SLUG:$TAG .
install: true
script:
  - true
after_success: |
  if [[ $TRAVIS_PULL_REQUEST == true ]]; then exit 0; fi
