doctrine:
    dbal:
        # MySQL
        server_version: '8.0'
        driver: pdo_mysql
        dbname:   '%env(resolve:MYSQL_DATABASE)%'
        host:     '%env(resolve:MYSQL_HOST)%'
        port:     '%env(resolve:MYSQL_PORT)%'
        user:     '%env(resolve:MYSQL_USER)%'
        password: '%env(resolve:MYSQL_PASSWORD)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
